sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
cache:
  directories:
  - $HOME/.cache/pip
install: pip install tox coveralls wheel
script: tox -e py${TRAVIS_PYTHON_VERSION/./}-django-${DJANGO/./}
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.9
    - python: 3.5
      env: DJANGO=1.7
after_success: coveralls
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: jazzband/django-queued-storage
    python: "2.7"
    condition: "$DJANGO = 1.9"
  password:
    secure: scGiNi9NXOdVaWzly7Tc65SBbC7iUVkcaO9ibBFfJq2QB0QM7es9QeXhpBz/biHbgCh40zuP8o2XmmsENxyaebb712k657YFS6fAcNmau7txCMOxDceQNoN/2OhSmGpYsegl8EdwBd4HsoB0fpLuq4bUg6OUkVkqR4pe4afq4O0=
